id: A91A9EDAA
title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:02:49.123644
  last_modified_at: 2022-03-01 03:02:49.123647
