id: A91A9EDAA
title: Prayer to the Lineage of the Bodhicaryāvatāra
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:02:49.120763
  last_modified_at: 2022-03-01 03:02:49.120768
