id: A91A9EDAA
title: Bodhicaryāvatāra Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:02:49.117424
  last_modified_at: 2022-03-01 03:02:49.117432
